### PR TITLE
"added dtos"

### LINKED ISSUE #14: user/books

### PR DESCRIPTION
**Pull request by RiyaRaj28**
resolves #14

### CODE REVIEW

**Review by Himasnhu-AT — APPROVED** [review]

**Comment by Himasnhu-AT** [comment]
Try to not make pr until the basic functionality is completed, send it as draft, when further edits need to be done

**Comment by Himasnhu-AT** [comment]
also in `user.module.ts`, why did you import `redis` and `authservice`

**Comment by RiyaRaj28** [comment]
> Try to not make pr until the basic functionality is completed, send it as draft, when further edits need to be done

okay

**Comment by RiyaRaj28** [comment]
> also in `user.module.ts`, why did you import `redis` and `authservice`

I didn't know how to access the user, so I was trying different things.

**Comment by Himasnhu-AT** [comment]
Closing this pr for time being, raise new one

**Comment by RiyaRaj28** [comment]
> Closing this pr for time being, raise new one

Okay

**Pull request closed without merging**
