### PR TITLE
Signup page + modified landing page

### PR DESCRIPTION
**Pull request by BhuvanSharma0711**

### CODE REVIEW

**Comment by Himasnhu-AT** [comment]
@BhuvanSharma0711 

its build is failing

```bash
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Failed to compile.
./src/components/Navigationbar.tsx:8:23
Type error: Cannot find module './ui/SunIcon' or its corresponding type declarations.
   6 | import Link  from 'next/link';
   7 | import {MoonIcon} from "./ui/MoonIcon";
>  8 | import {SunIcon} from "./ui/SunIcon";
     |                       ^
   9 | import { Switch } from '@nextui-org/switch';
  10 |
  11 |
Error: Command "npm run build" exited with 1

```

check where it's failing and correct that

**Comment by BhuvanSharma0711** [comment]
okk

**Comment by BhuvanSharma0711** [comment]
i think its resolved now i will create a new pull request with email
verification page asap

**Comment by Himasnhu-AT** [comment]
@BhuvanSharma0711 you don't need to close pr, the commits made will be updated to pr automatically

**Pull request closed without merging**
